version: '3.8'

services:
  api:
    build: .
    container_name: api-security-lab
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./logs:/app/logs
      - db-data:/app/data
    environment:
      NODE_ENV: development
      DATABASE_URL: file:/app/data/dev.db
      JWT_SECRET: dev-jwt-secret-change-in-prod
      JWT_REFRESH_SECRET: dev-refresh-secret
      JWT_STEP_UP_SECRET: dev-step-up-secret
      PORT: 3000
    command: npm run dev

volumes:
  db-data:

